export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const TOO_MANY_ATTEMPTS_TRY_LATER = 'TOO_MANY_ATTEMPTS_TRY_LATER';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
